spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: starrate
          destination: talent-exchange-system
          contentType: application/json
        event-out:
          destination: talent-exchange-system
          contentType: application/json
  datasource:
    url: jdbc:mysql://localhost:3306/tes
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8082